### ISSUE TITLE
nav bar 

### ISSUE THREAD

**Issue by ujjwalshivhare** [SpandanM110/De-SchoolMate#15]

**Comment by ujjwalshivhare** [comment]
sir,
can you add hacktoberfest label and can you merge this issue

**Comment by Rajeevjewar** [comment]
Hey @ujjwalshivhare, Could you describe the issue?

**Comment by SpandanM110** [comment]
Now I think the issue of navbar is solved now you can contribute to new issues as well.

**Comment by Rajeevjewar** [comment]
Ok...

**Comment by SpandanM110** [comment]
Done
