### ISSUE TITLE
Fix the buttons of navbar

### ISSUE THREAD

**Issue by SpandanM110** [SpandanM110/De-SchoolMate#25]
The buttons of navbar need to be fixed.
![image](https://github.com/SpandanM110/De-SchoolMate/assets/95229740/67c9b593-11ce-4d03-9858-4c4afd5a66e5)

**Comment by lavanderhoney** [comment]
I'm ready to work on this issue, although it's unclear what "fixed" means here. Can you please specify what would you liked to get fixed?

**Comment by lavanderhoney** [comment]
So you want to improve the styling of the navbar and make it look like the image provided in the README file?

**Comment by SpandanM110** [comment]
Yes

**Comment by SpandanM110** [comment]
@vedantheda you can work on the bug or latest new issues as well.

**Comment by SpandanM110** [comment]
Navbar changes done
