### ISSUE TITLE
Open App> Gallery look and designs from the landing page

### ISSUE THREAD

**Issue by SpandanM110** [SpandanM110/De-SchoolMate#33]
Take inspiration from the landing page click on Open APP and a gallery appears I want to redesign the gallery taking inspiration from the landing page. 
Folks Do star the repo after your priceless effort and contributions.

**Comment by coder-pink** [comment]
@SpandanM110 okay I would like to work on it. Please assign it to me.

**Comment by SpandanM110** [comment]
All the best there you go

**Comment by Rajeevjewar** [comment]
Text in the Feature section is not readable, legible, and appealing. Even the whole design of the project is not consistent.
<img width="1063" alt="Screenshot 2023-10-19 at 6 05 20 PM" src="https://github.com/SpandanM110/De-SchoolMate/assets/97542658/a2b65f64-d93e-4e4a-aa36-52a297e9955e">

**Comment by Rajeevjewar** [comment]
@SpandanM110 Thank you for assigning me.
