### ISSUE TITLE
Home Button: add home button on every feature page

### ISSUE THREAD

**Issue by Mahek-05** [SpandanM110/De-SchoolMate#41]
it would be very convenient if there is home button on individual feature pages, so that users can return to the homepage from any fetaure page.

For eg. if there is a home button on todolist page then the user dont have to enter url to go to homepage but can simply click on home button.

additionally a feature button can also be added on every feature page so that user can direct to features list from any feature page.

for eg. if user is on todolist page then user can click on features button and go to features page

**Comment by SpandanM110** [comment]
Ok I got your POV so all the best I am assigning it to you.

**Comment by Mahek-05** [comment]
thank you. I am starting to work on it.

**Comment by Mahek-05** [comment]
Done.
I have sent the pull request, review and merge it.
It would be awesome if you consider adding hacktoberfest-accepted to this.
If anything else has to be done, please tell me, I will be happy to do it.

**Comment by Sou6161** [comment]
I want to work in this issue plzz assign me

**Comment by SpandanM110** [comment]
@Sou6161 you can work on new issue if you want

**Comment by maskfool** [comment]
is this issue resolved?

**Comment by SpandanM110** [comment]
Yes it's done. Sorry I am Closing it
