### ISSUE TITLE
Bug Issue solve

### ISSUE THREAD

**Issue by SpandanM110** [SpandanM110/De-SchoolMate#43]
The bug is when you click on the link https://de-school-mate-tau.vercel.app/ and the click on Open APP it constantly opens in new tab I want only 1 tab should be operable throughout the tour of the website.

**Comment by Dushyant-Mahto** [comment]
I'd like to work on this.

**Comment by sid172014** [comment]
@SpandanM110 lemme fix this , please assign it to me.

**Comment by SpandanM110** [comment]
Assigning both of you or @sid172014 take application feature designing and make a PR of it or @Dushyant-Mahto you can work on the bug as well.

**Comment by sid172014** [comment]
Alright

**Comment by SpandanM110** [comment]
Solved Finally Thanks to @Dushyant-Mahto
