### ISSUE TITLE
Fix: Footer Changes

### ISSUE THREAD

**Issue by coder-pink** [SpandanM110/De-SchoolMate#47]
**Description**
Make the UI of Website Footer better.

![BB](https://github.com/SpandanM110/De-SchoolMate/assets/78805055/404483f5-605b-4a06-86cb-8c5f10a895d0)

**Comment by coder-pink** [comment]
@SpandanM110 can you add label?

**Comment by SpandanM110** [comment]
@coder-pink Can you give a new color schematic then I will merge it happily

**Comment by coder-pink** [comment]
> @coder-pink Can you give a new color schematic then I will merge it happily

@SpandanM110 
this one:
<img width="772" alt="Capture" src="https://github.com/SpandanM110/De-SchoolMate/assets/78805055/9b2e9293-c0b8-4892-8e11-361e979a613b">

or this one:
<img width="904" alt="11" src="https://github.com/SpandanM110/De-SchoolMate/assets/78805055/85cbcd59-b770-499e-bbb0-f434ddcdd128">

**Comment by SpandanM110** [comment]
Which one looks better I guess black one
