### ISSUE TITLE
Design the Pomodoro Timer referring the landing page

### ISSUE THREAD

**Issue by SpandanM110** [SpandanM110/De-SchoolMate#52]
![Screenshot 2023-10-20 180441](https://github.com/SpandanM110/De-SchoolMate/assets/95229740/fd315faf-baae-4532-897f-30da848643ef)

This the landing page now make a better looks for the pomodoro timer with better UI and Looks

![image](https://github.com/SpandanM110/De-SchoolMate/assets/95229740/e3157e09-1ae9-471f-95fe-31cd94d507a7)

**Comment by ojasaklechayt** [comment]
@SpandanM110 can you assign this to me ?

**Comment by SpandanM110** [comment]
Sure @ojasaklechayt

**Comment by SpandanM110** [comment]
Done Thanks To @ojasaklechayt !
