### ISSUE TITLE
There is no back to top button on the landing page

### ISSUE THREAD

**Issue by venom-2** [SpandanM110/De-SchoolMate#70]
The landing page lacks the back-to-top button which is essential for UI/UX
![Screenshot 2023-10-23 120338](https://github.com/SpandanM110/De-SchoolMate/assets/103876428/7cdebe52-f39c-4aae-9fe2-f681c9a9378c)

**Comment by venom-2** [comment]
Kindly assign this issue to me under hacktoberfest tag

**Comment by SpandanM110** [comment]
@venom-2 There you go!

**Comment by Prakharpandey007** [comment]
Please assign me this issue . I am interested to work on this issue.Looking for positive response.
thank you .

**Comment by Pritam-2002** [comment]
close this issue it is solved ...
