### ISSUE TITLE
.gitIgnore file is missing.

### ISSUE THREAD

**Issue by Rajeevjewar** [SpandanM110/De-SchoolMate#84]
The .gitIgnore file is crucial for developers to specify which files and directories should be ignored by Git. It helps keep the repository clean by excluding temporary files, build artifacts, and sensitive information, improving collaboration and avoiding clutter.

**Comment by beingsie** [comment]
I can work on this issue. Besides the common ignored files are there any extra files you would like added to this?

**Comment by SpandanM110** [comment]
@beingsie Fix the bug

**Comment by beingsie** [comment]
> @beingsie Fix the bug

Issue has been fixed in PR #89. Please advise if you will be able to assign appropriate Hacktoberfest labels.
